Resources:
  ECRA:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: blackdoctor-ecr-nonprod-xxx1
      ImageScanningConfiguration:
        ScanOnPush: true
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ba0e877d-60f3-4b27-ab9b-113b2bfab0a6
  ECRB:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: blackdoctor-ecr-prod-xxx1
      ImageScanningConfiguration:
        ScanOnPush: true
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 99b59d3a-06b9-4982-aec1-964a7d32cd36