Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: Fargate-ECS-Cluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
       - CapacityProvider: FARGATE
         Weight: 1
       - CapacityProvider: FARGATE_SPOT
         Weight: 1