Resources:
  EC2SGRDS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: access-to-rds-sg
      GroupDescription: 'Access_to_RDS_system'
      VpcId: 
        Fn::ImportValue: myVPCexport
      SecurityGroupIngress:
         - IpProtocol : tcp
           FromPort : 5432
           ToPort : 5432
           CidrIp : 0.0.0.0/0
      SecurityGroupEgress:
         - IpProtocol : tcp
           FromPort : 5432
           ToPort : 5432
           CidrIp : 0.0.0.0/0  
  
  SUBNETRDSA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Fn::ImportValue: myVPCexport
      CidrBlock: 10.10.10.0/24
      AvailabilityZone: "eu-west-1a"
      Tags:
      - Key: stack
        Value: production

  SUBNETRDSB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Fn::ImportValue: myVPCexport
      CidrBlock: 10.10.20.0/24
      AvailabilityZone: "eu-west-1b"
      Tags:
      - Key: stack
        Value: production

  
  SUBNETRDSC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Fn::ImportValue: myVPCexport
      CidrBlock: 10.10.30.0/24
      AvailabilityZone: "eu-west-1c"
      Tags:
      - Key: stack
        Value: production      
  
  RDSGROUPA:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Group_for_RDS
      SubnetIds:
        - !Ref SUBNETRDSA
        - !Ref SUBNETRDSB
        - !Ref SUBNETRDSC

  MyDbSecurityByCIDRIPsGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      EC2VpcId:
        Fn::ImportValue: myVPCexport
      GroupDescription: Ingress for CIDRIP
      DBSecurityGroupIngress:
        CIDRIP: "10.10.0.0/16"

  RDSDBA:
    Type: AWS::RDS::DBInstance
    Properties:
      VPCSecurityGroups:
       - !Ref EC2SGRDS
      DBSecurityGroups:
       - !Ref MyDbSecurityByCIDRIPsGroup
      DBName: MYSQLDBName
      AllocatedStorage: '5'
      DBInstanceClass: db.m5.large
      Engine: "postgres"
      EngineVersion: "13.3"
      MasterUsername: superadmin
      MasterUserPassword: passw0rd!!
      DBSubnetGroupName: !Ref RDSGROUPA
    
