# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:           
            - echo "Your build and test goes here..."
            - rm -rf package-lock.json
            - rm -rf node_modules
            - npm install
            - npm run test
            - npm run build

      - step:
          name: 'Lint'
          script:
            - echo "Your linting goes here..."
            - rm -rf package-lock.json
            - rm -rf node_modules
            - npm install
            - npm run lint
      
