image: python:3.7.3

pipelines:
#  default:
  branches:
    main:
#Build docker container
      - step:
          name: Build and push Docker image
          caches:
           - pip
          services:
            - docker            
          script:
           - pip install awscli
           - eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
           - docker build -t $IMAGE_NAME .
           - export IMAGE_ID=`docker images -q $IMAGE_NAME`
           - docker tag $IMAGE_ID $IMAGE_REPOSITORY:fastapi-latest
           - docker push $IMAGE_REPOSITORY     
#Force AWS ECS Deployment
      - step:
         name: Deploy to AWS ECS Cluster
         oidc: true
         script:
          - pipe: atlassian/aws-ecs-deploy:1.6.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ECS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_ECS_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              CLUSTER_NAME: $CLUSTER_NAME
              SERVICE_NAME: $SERVICE_NAME
              FORCE_NEW_DEPLOYMENT: 'true'
              WAIT: 'true'
              
